### ISSUE TITLE
A question about deconfounder_tutorial

### ISSUE THREAD

**Issue by jiazhao97** [blei-lab/deconfounder_tutorial#4]
Thank you for providing this detailed tutorial.

I want to ask a question. After training the factor model, you use the following codes to generate samples (x_generated).
```
 with ed.interception(replace_latents(w_sample, z_sample)):
            generate = ppca_model(
            data_dim=data_dim, latent_dim=latent_dim,
            num_datapoints=num_datapoints, stddv_datapoints=stddv_datapoints)
 with tf.Session() as sess:
        x_generated, _ = sess.run(generate)
```

However, in the ppca_model, the mean matrix is masked by "1-holdout_mask":
```
x = ed.Normal(loc=tf.multiply(tf.matmul(z, w), 1-holdout_mask),
                scale=stddv_datapoints * tf.ones([num_datapoints, data_dim]),
                name="x")
```

Should we remove the mask "1-holdout_mask" when generating samples and then mask it with "holdout_mask" instead?

**Comment by yixinwang** [comment]
Yes. I just pushed an update. Thank you!
