### ISSUE TITLE
Low p-value in section 2.3

### ISSUE THREAD

**Issue by BRim28** [blei-lab/deconfounder_tutorial#6]
We say that we pass the predictive check if the p-value is not less and the obtained p-value in section 2.3 is very less (0.1020). This means that we haven't passed the check. Please correct me if I am wrong.

**Comment by yixinwang** [comment]
Loosely, the larger the p-value is, the better the model fit is. So larger p-values are preferred. Moreover, the threshold of 0.1 for the p-value is a subjective choice to decide about passing or failing the check. We'd be cautious about using a model with a p-value only slightly 0.1.
